name: ğŸ‘‹ Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello there ğŸ‘‹
          Thanks for submitting your first issue to the Retro Home project ğŸ› We'll try and take a look at your issue soon â²

          In the meantime you might want to join the [Wimpy's World Discord](https://wimpysworld.io/discord) ğŸ—£ where we have a large community of Linux ğŸ§ enthusiasts and passionate open source developers ğŸ§‘â€ğŸ’» and a support channel for this project.

          You might also be interested in following [Wimpy's World Twitch ğŸ“¡ channel](https://twitch.tv/WimpysWorld) where Wimpy streams let's code videos, including this project, several times a week. A back catalog of past live streams and other Linux ğŸ§ and Raspberry Pi ğŸ¥§ related content is available on [Wimpy's World YouTube ğŸ“º channel](https://youtube.com/WimpysWorld).
        pr-message: |
          Hello there ğŸ‘‹
          Thanks for submitting your first pull request to the Retro Home project ğŸ’ª We'll try to review your pull request soon â²

          In the meantime you might want to join the [Wimpy's World Discord](https://wimpysworld.io/discord) ğŸ—£ where we have a large community of Linux ğŸ§ enthusiasts and passionate open source developers ğŸ§‘â€ğŸ’» and a support channel for this project.

          You might also be interested in following [Wimpy's World Twitch ğŸ“¡ channel](https://twitch.tv/WimpysWorld) where Wimpy streams let's code videos, including this project, several times a week. A back catalog of past live streams and other Linux ğŸ§ and Raspberry Pi ğŸ¥§ related content is available on [Wimpy's World YouTube ğŸ“º channel](https://youtube.com/WimpysWorld).
